SpringCRUD to mongodb
mykytka235/SpringCRUD pull request #1
Opened 2020-12-25 18:13 UTC by skankhunt220

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +			User _user = userRepository.save(new User(user.getFirstName(), user.getMiddleName(), user.getLastName()));
Why are you sending a new `user` to `save`? You got it in `RequestBody`, so why not send it and create a new `user`?

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +			return new ResponseEntity<>(null, HttpStatus.INTERNAL_SERVER_ERROR);
try `ResponseEntity.status(505).build() ` and if return value is useful: `ResponseEntity.status(201).body(user)`

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +	@PostMapping("/")
remove ("/") is redundant

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +	public ResponseEntity<User> createUser(@RequestBody User user) {
The class named a `UserController`, so don`t need add to method names **user** prefix

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +	public ResponseEntity<User> getUserById(@PathVariable("id") String id) {
same here

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +	public ResponseEntity<User> updateUser(@PathVariable("id") String id, @RequestBody User user) {
same here

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +	public ResponseEntity<HttpStatus> deleteUser(@PathVariable("id") String id) {
same here

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +			User _user = userData.get();
What a reason to create a new `user`? You can use `userData.get()`.

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/api/controller/UserController.java
> +			return new ResponseEntity<>(HttpStatus.NO_CONTENT);
You can choose not to return anything after deleting

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/configuration/ApplicationConfig.java
> +@EnableMongoRepositories(basePackages = "com.skankhunt220.repository")
it's redundant remove it, spring very smart, and it can find your repository. It's can be helpful if you have two data source

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/service/UserService.java
> -public class UserService {
I see no reason to delete this

2021-01-15 06:48 UTC, MaxSasha commented on src/main/java/com/skankhunt220/configuration/ApplicationConfig.java
> +	protected String getDatabaseName() {
You can create a application.property file and Spring autoconfigure your mongoDb(this file can be place in **src/main/resources**)
Example file:
```
mongodb.database=test
mongodb.host=localhost
mongodb.port=27017
```
and etc.

2021-01-18 08:44 UTC, koropatva requested changes

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/config/MultipleMongoConfig.java
> +		return new SimpleMongoClientDatabaseFactory(MongoClients.create("mongodb://localhost:27017/"), mongo.getDatabase());
Move mongodb configs into property

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/config/MultipleMongoConfig.java
> +public class MultipleMongoConfig {
Split diff confgs into different files or group them togather

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/config/MultipleMongoConfig.java
> +		return new SimpleMongoClientDatabaseFactory(MongoClients.create("mongodb://localhost:27017/"), mongo.getDatabase());
Same

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/config/UserAutoConfiguration.java
> +@EnableMongoRepositories(basePackages = "com.skankhunt220.repository.user", mongoTemplateRef = "primaryMongoTemplate")
Move on this config configurations of primaryMongoTemplate, it will be more readible

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/entity/City.java
> +	public City(String name, String zipCode)
Use lombock for it, and don't forget to format your code

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/entity/City.java
> +	private @Id String id;
put annotation above varibale initialization

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/entity/User.java
> +	private @Id String id;
same

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/entity/User.java
> +	public User(String firstName, String middleName, String lastName)
same

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +	private CityRepository cityRepository;
instead of @Autowired use `final static` and annotation from lombock @REquired ArgConstructor

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +	public ResponseEntity<City> createCity(City city) {
Remove city from name, it is surpluses

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +	public ResponseEntity<City> readCity(String cityId) {
Sme

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +		} catch (Exception e) {
log error, always

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +		if (cityData.isPresent()) {
Don't split response on found not found, just return response, if response is null, then object is not found

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +	public ResponseEntity<City> updateCity(String cityId, City city) {
same

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +		if (cityData.isPresent()) {
it doesn't make sense, just update it without checking

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +			cityData.get().setZipCode(city.getZipCode());
you forgot to update city object ;) and use transformer, for data population

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +	public void deleteCity(String cityId) {
same

2021-01-18 08:44 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +		} catch (Exception e) {}
?

2021-01-19 07:39 UTC, koropatva requested changes

2021-01-19 07:39 UTC, koropatva commented on src/main/java/com/skankhunt220/service/UserService.java
> +		return ResponseEntity.status(HttpStatus.CREATED).body(userRepository.save(User.builder()
use transformer to populate User object

2021-01-19 07:39 UTC, koropatva commented on src/main/java/com/skankhunt220/service/CityService.java
> +				.body(cityRepository.save(City.builder().name(city.getName()).zipCode(city.getZipCode()).build()));
saem here, you should use city builder for transformation

2021-01-19 07:45 UTC, insanejd commented on src/main/java/com/skankhunt220/api/transformer/Transformer.java
> +		return User.builder().id(id).firstName(user.getFirstName()).middleName(user.getMiddleName())
Your code is difficult to read, I suggest formatting code like this: 
```
return User.builder()
        .id(id)
        .firstName(user.getFirstName())
        .middleName(user.getMiddleName())
        .lastName(user.getLastName())
        .build();
```
Change here and everywhere

2021-01-19 07:45 UTC, insanejd commented on src/main/java/com/skankhunt220/service/CityService.java
> +				.body(cityRepository.save(City.builder().name(city.getName()).zipCode(city.getZipCode()).build()));
What is the reason for creating a new `Сity`? You can use the object that came in the method

2021-01-19 07:45 UTC, MaxSasha commented on src/main/java/com/skankhunt220/service/CityService.java
> +		return ResponseEntity.status(HttpStatus.OK).body(cityRepository.save(transform(city, cityId)));
You need to transform city in your controller.
![изображение](https://user-images.githubusercontent.com/62429027/105002978-bf5bce80-5a3a-11eb-962d-77660b8b867f.png)

2021-02-08 16:08 UTC, closed without merging